export const SET_CURRENT_PAGE = "SET_CURRENT_PAGE";
export const SET_CONTINENT_FILTER = "SET_CONTINENT_FILTER";
export const SET_ACTIVITY_FILTER = "SET_ACTIVITY_FILTER";
export const SET_SORT = "SET_SORT";
export const SET_SEARCH_NAME = "SET_SEARCH_NAME";
export const CLEAR_FILTERS = "CLEAR_FILTERS";
